version: "3.7"

services:
  # php 8.0
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
        - "9000:9000"
    networks:
        - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root_secret'
      MYSQL_DATABASE: 'dream_team'
      MYSQL_USER: 'unixlira'
      MYSQL_PASSWORD: 'secret'
      MYSQL_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init-user.sql
    volumes:
      - ./docker/mysql/dbdata:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
